import type { CurrentStayProperty } from '../src/store/redux/slices/currentStaySlice';

export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  LoginPin: undefined;
  Home: undefined;
  Settings: undefined;
  Signup: undefined;
  BasicInfo: undefined;
  Email: undefined;
  VerifyEmailScreen: undefined;
  CreatePassword: undefined;
  Success: undefined;
  Reactivate: undefined;
  ResetPassword: undefined;
  ResetPasswordSent: undefined;
  ProfileSetup: undefined;
  Facilities: undefined;
  Floors: undefined;
  Rooms: undefined;
  Verify: undefined;
  RulesScreen: undefined;
  FoodScreen: undefined;
  CreateMPINScreen: undefined;
  Notifications: undefined;
  Profile: undefined;
  Profile2: undefined;
  CompleteProfile: undefined;
  CompleteProfileDocs: undefined;
  SearchAdmin: undefined;
  AdminDetails: undefined;
  LocationResults: undefined;
  SearchResultDetails: undefined;
  TicketsScreen: undefined;
  TicketChat: { ticketId?: string };
  CreateRequest: undefined;
  ReloginMobileScreen: undefined;
  PaymentDueScreen: undefined;
  CreateNewMPIN: undefined;
  PropertyDetailsScreen: { property?: CurrentStayProperty };
  PropertyListScreen: undefined;
  MoveOutRequestScreen: { property?: CurrentStayProperty };
  MoveOutStatusScreen: undefined;
};
